import { apiFetch } from "@/lib/api-client";
import type { CreatePromoInput, BulkPromoResult, PromoDTO, PromoListResponse, PromoValidationResult, UpdatePromoInput } from "@/lib/promo-types";
export interface PromoListParams {page?:number;pageSize?:number;search?:string;tipe?:string;sortBy?:string;sortOrder?:"asc"|"desc";}
function qs(p:PromoListParams){const q=new URLSearchParams();for(const [k,v] of Object.entries(p)){if(v!==undefined&&v!=="")q.set(k,String(v));}return q.toString();}
export function listPromos(p:PromoListParams={}):Promise<PromoListResponse>{const q=qs(p);return apiFetch(`/api/backoffice-sudirja/promo${q?`?${q}`:""}`);}
export function createPromo(input:CreatePromoInput):Promise<PromoDTO>{return apiFetch("/api/backoffice-sudirja/promo",{method:"POST",body:JSON.stringify(input)});}
export function updatePromo(id:number,input:UpdatePromoInput):Promise<PromoDTO>{return apiFetch(`/api/backoffice-sudirja/promo/${id}`,{method:"PATCH",body:JSON.stringify(input)});}
export function deletePromo(id:number){return apiFetch<{message:string}>(`/api/backoffice-sudirja/promo/${id}`,{method:"DELETE"});}
export function bulkCreatePromos(rows:CreatePromoInput[]):Promise<BulkPromoResult>{return apiFetch("/api/backoffice-sudirja/promo/bulk",{method:"POST",body:JSON.stringify({rows})});}
export function validatePromoVoucher(kode:string,subtotal:number):Promise<PromoValidationResult>{const q=new URLSearchParams({kode,subtotal:String(subtotal)});return apiFetch(`/api/backoffice-sudirja/promo/validate?${q.toString()}`);}
export function downloadPromoCsv(items:PromoDTO[]){const headers=["ID","Kode","Nama","Tipe","Deskripsi","Nilai Diskon","Minimal Belanja","Maksimal Diskon","Tanggal Mulai","Tanggal Berakhir","Batas Kuota","Jumlah Digunakan","Status"];const esc=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;const body=items.map(p=>[p.id,p.kode,p.nama,p.tipe,p.deskripsi,p.nilaiDiskon,p.minimalBelanja,p.maksimalDiskon??"",p.tanggalMulai,p.tanggalBerakhir,p.batasKuota,p.jumlahDigunakan,p.isActive?"Aktif":"Nonaktif"].map(esc).join(","));const blob=new Blob(["\uFEFF",[headers.join(","),...body].join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`data-promo-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);}
